function label = get_label(path)
    path_split=strsplit(path,'\');
    str_label=strsplit(path_split{end},'_');
    label= '';
    % Assignin variable based on file name
    if strcmp(str_label{2},'concentration')||...
            strcmp(str_label{end},'concentration.csv') || ...
            sum(str_label{1}(1:3)=='Con')==3||...
            strcmp(str_label{2},'attention')||...
            strcmp(str_label{2},'attention.txt')
        if (~strcmp(str_label{3},'high'))
           label=0;
        else
           label=1;
        end
    end
    if strcmp(str_label{2},'rest')||...
            strcmp(str_label{end},'rest.csv')|| ...
            sum(str_label{1}(1:3)=='Res')==3||...
            strcmp(str_label{2},'inattention')||...
            strcmp(str_label{2},'inattention.txt')
        label=-1;
    end
end